# Server Configuration File
server:
  port: 80
  static-dir: /app/static

logging:
  enabled: true

cache:
  enabled: true
  time_in_hours: 4

lru:
  enabled: true

tls:
  port: 443
  enabled: true
  crt_file: /certs/ardu-badge.cert
  key_file: /certs/ardu-badge.key

libraries:
  refresh_rate_hours: 1